# -*- coding: utf-8 -*-
"""temperatue converter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4iOYsZqRVDvgI8CK1xmKJqy16zWf6M4
"""

# Function to convert Celsius to Fahrenheit
def celsius_to_fahrenheit(celsius):
    return (celsius * 9/5) + 32

# Function to convert Fahrenheit to Celsius
def fahrenheit_to_celsius(fahrenheit):
    return (fahrenheit - 32) * 5/9

# Ask the user for input
temp = float(input("Enter the temperature: "))
unit = input("Is this in Celsius or Fahrenheit? (C/F): ").strip().upper()

# Conditional conversion
if unit == "C":
    converted = celsius_to_fahrenheit(temp)
    print(f"{temp}°C is {converted:.2f}°F")
elif unit == "F":
    converted = fahrenheit_to_celsius(temp)
    print(f"{temp}°F is {converted:.2f}°C")
else:
    print("Invalid unit! Please enter 'C' for Celsius or 'F' for Fahrenheit.")





